# Generated by Django 3.1.2 on 2020-10-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Select Status', 'Select Status'), ('Backlog', 'Backlog'), ('Working in Progress', 'Working in Progress'), ('Testing', 'Testing'), ('Done', 'Done')], max_length=50, null=True)),
                ('work_creat_date', models.DateTimeField(auto_now_add=True)),
                ('work_code_date', models.DateTimeField(blank=True, null=True)),
                ('work_test_date', models.DateTimeField(blank=True, null=True)),
                ('work_done_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
